version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: contentful
    versions:
    - 8.1.7
    - 8.1.8
    - 8.1.9
    - 8.2.0
    - 8.2.1
    - 8.3.0
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
  - dependency-name: eslint-plugin-svelte3
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.0
    - 2.4.1
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: prettier-plugin-svelte
    versions:
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.1.6
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.5
    - 4.6.6
    - 4.6.7
    - 4.6.8
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.6
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: axios
    versions:
    - 0.21.1
